Add health-check

diff --git a/roles/express-api/templates/start-express-container.sh.j2 b/roles/express-api/templates/start-express-container.sh.j2
--- a/roles/express-api/templates/start-express-container.sh.j2
+++ b/roles/express-api/templates/start-express-container.sh.j2
@@ -1,5 +1,6 @@
 api_name=$1
 api_path=/apis/apis/$api_name
+env=/apis/env/$api_name.env
 
 cd $api_path
 
@@ -35,10 +36,16 @@ docker import $archive $api_name:$tag
 
 docker run -d \
            --workdir /usr/src/$api_name \
+           --env-file $env \
            --volume /apis/keytool_files:/usr/src/$api_name/keytool_files \
            --volume $api_path/logs:/usr/src/$api_name/logs \
            --network host \
-           --user=$uid:$gid \
+           --health-cmd='curl -k -fsS --user $USER:$PASSWD https://localhost:$PORT/api/v1' \
            --name $api_name \
            $api_name:$tag \
            gulp run
+
+if [[ ! $(docker ps -q -f name=$api_name) ]]; then
+   echo "ERROR: Container not running"
+   exit 1
+fi
