add logging

diff --git a/roles/docker-garbage-collection/templates/garbage-collect-docker.sh.j2 b/roles/docker-garbage-collection/templates/garbage-collect-docker.sh.j2
--- a/roles/docker-garbage-collection/templates/garbage-collect-docker.sh.j2
+++ b/roles/docker-garbage-collection/templates/garbage-collect-docker.sh.j2
@@ -5,9 +5,20 @@
 #   preventing any image removal
 
 stopped_container_sed_pattern="{{stopped_container_sed_pattern}}"
-backup_images_dir="{{garbage_home}}/{{backup_images_dir}}"
+backup_images_path="{{garbage_home}}/{{backup_images_dir}}"
+log_path="{{garbage_home}}/{{log_file}}"
 
 {% raw %}
+
+###
+# log()
+# Description: Appends the log file with a timestamp and message
+# Parameters: $1 is the message.
+###
+log()
+{
+    echo $(date) $1 >> ${log_path}
+}
 
 ###
 # remove_image()
@@ -28,8 +39,17 @@ remove_image()
     container_id=$(echo $removal_output | sed -n -e "$stopped_container_sed_pattern")
     if [ $removal_exit -eq 1 ] && [ -n "$container_id" ]
     then
+        log "Stopped container $container_id prevented removal of image $id"
         docker rm $container_id
-        remove_image $id
+        if [ $? -eq 1 ]
+        then
+            log "Failed removing container $container_id"
+        else
+            log "Removed container $container_id"
+            remove_image $id
+        fi
+    else
+        log "Removed image $id"
     fi
 }
 
@@ -44,12 +64,16 @@ main()
     for id in "${dangling_ids[@]}"
     do
         # backup dangling image
-        $(docker save -o $backup_images_dir/$id.tar $id)
-
-        # remove dangling image
-        remove_image $id
+        docker save -o $backup_images_path/$id.tar $id
+        if [ $? -eq 0 ]
+        then
+            log "Backed up image $id"
+            # remove dangling image
+            remove_image $id
+        else
+            log "Backup of image $id failed"
+        fi
     done
-
 }
 
 main
