check if container is running

diff --git a/roles/api-web/templates/hubot-start.j2 b/roles/api-web/templates/hubot-start.j2
--- a/roles/api-web/templates/hubot-start.j2
+++ b/roles/api-web/templates/hubot-start.j2
@@ -18,3 +18,8 @@ echo "Start container"
 docker build -t $CONTAINER_NAME {{ hubot_path|quote }}
 
 docker run --volume {{ hubot_path|quote }}/local.env:/src/hubot/local.env:ro --name="$CONTAINER_NAME" $CONTAINER_NAME
+
+if [[ ! $(docker ps -q -f name=$CONTAINER_NAME) ]]; then
+    echo "ERROR: Container not running"
+    exit 1
+fi
